# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: hassmic.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
    Optional,
)

import betterproto


class MediaPlayerState(betterproto.Enum):
    """
    https://developer.android.com/reference/androidx/media3/common/Player.State
    """

    STATE_UNKNOWN = 0
    STATE_IDLE = 1
    STATE_BUFFERING = 2
    STATE_PLAYING = 3
    STATE_PAUSED = 4


class MediaPlayerCommandId(betterproto.Enum):
    COMMAND_UNKNOWN = 0
    COMMAND_PLAY = 1
    COMMAND_PAUSE = 2
    COMMAND_STOP = 3


class MediaPlayerId(betterproto.Enum):
    """The different media players available"""

    ID_UNKNOWN = 0
    ID_PLAYBACK = 1
    """The normal music/audio playback player"""

    ID_ANNOUNCE = 2
    """The announce player"""


class LogSeverity(betterproto.Enum):
    SEVERITY_UNKNOWN = 0
    SEVERITY_DEBUG = 1
    SEVERITY_INFO = 2
    SEVERITY_WARNING = 3
    SEVERITY_ERROR = 4


@dataclass(eq=False, repr=False)
class SavedSettings(betterproto.Message):
    """Information saved and loaded between runs of the hassmic app"""

    announce_volume: Optional[float] = betterproto.float_field(1, optional=True)
    """The last volume of the `announce` player"""

    playback_volume: Optional[float] = betterproto.float_field(2, optional=True)
    """The last volume of the `playback` player"""

    hassmic_uuid: str = betterproto.string_field(3)
    """Hassmic UUID"""

    device_name: str = betterproto.string_field(4)
    """Device name"""

    wakeword_sound: str = betterproto.string_field(6)
    """Wakeword Sound"""


@dataclass(eq=False, repr=False)
class ClientInfo(betterproto.Message):
    """Information that the client sends about itself"""

    version: str = betterproto.string_field(1)
    """The version, for example "0.9.2"""

    uuid: str = betterproto.string_field(2)
    """The uuid of this client"""


@dataclass(eq=False, repr=False)
class Ping(betterproto.Message):
    """A ping message"""

    pass


@dataclass(eq=False, repr=False)
class AudioData(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class MediaPlayerCommand(betterproto.Message):
    """A command paired with a player"""

    id: "MediaPlayerId" = betterproto.enum_field(1)
    command: "MediaPlayerCommandId" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class MediaPlayerVolume(betterproto.Message):
    """A media player has changed volume"""

    player: "MediaPlayerId" = betterproto.enum_field(1)
    volume: float = betterproto.float_field(2)


@dataclass(eq=False, repr=False)
class DeviceVolume(betterproto.Message):
    """The device volume has changed"""

    volume: float = betterproto.float_field(1)


@dataclass(eq=False, repr=False)
class MediaPlayerStateChange(betterproto.Message):
    """A media player has changed state"""

    player: "MediaPlayerId" = betterproto.enum_field(1)
    new_state: "MediaPlayerState" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class WyomingEvent(betterproto.Message):
    """
    An event from the wyoming server
     event definitions are captured from the wyoming project source

     up to date info messages are here, not the main page -
     https://github.com/rhasspy/wyoming/blob/master/wyoming/info.py
    """

    raw_json: str = betterproto.string_field(1)
    """The raw json of the message"""

    payload: bytes = betterproto.bytes_field(2)
    describe: "WyomingEventDescribe" = betterproto.message_field(3, group="event")
    info: "WyomingEventInfo" = betterproto.message_field(4, group="event")
    ping: "WyomingEventPing" = betterproto.message_field(5, group="event")
    pong: "WyomingEventPong" = betterproto.message_field(6, group="event")
    audio_chunk: "WyomingEventAudioChunk" = betterproto.message_field(7, group="event")
    audio_start: "WyomingEventAudioStart" = betterproto.message_field(8, group="event")
    audio_stop: "WyomingEventAudioStop" = betterproto.message_field(9, group="event")
    played: "WyomingEventPlayed" = betterproto.message_field(10, group="event")
    detect: "WyomingEventDetect" = betterproto.message_field(11, group="event")
    detection: "WyomingEventDetection" = betterproto.message_field(12, group="event")
    not_detected: "WyomingEventNotDetected" = betterproto.message_field(
        13, group="event"
    )
    run_pipeline: "WyomingEventRunPipeline" = betterproto.message_field(
        14, group="event"
    )
    run_satellite: "WyomingEventRunSatellite" = betterproto.message_field(
        15, group="event"
    )
    pause_satellite: "WyomingEventPauseSatellite" = betterproto.message_field(
        16, group="event"
    )
    satellite_connected: "WyomingEventSatelliteConnected" = betterproto.message_field(
        17, group="event"
    )
    satellite_disconnected: "WyomingEventSatelliteDisconnected" = (
        betterproto.message_field(18, group="event")
    )
    streaming_started: "WyomingEventStreamingStarted" = betterproto.message_field(
        19, group="event"
    )
    streaming_stopped: "WyomingEventStreamingStopped" = betterproto.message_field(
        20, group="event"
    )
    transcribe: "WyomingEventTranscribe" = betterproto.message_field(21, group="event")
    transcript: "WyomingEventTranscript" = betterproto.message_field(22, group="event")
    synthesize: "WyomingEventSynthesize" = betterproto.message_field(23, group="event")
    voice_started: "WyomingEventVoiceStarted" = betterproto.message_field(
        24, group="event"
    )
    voice_stopped: "WyomingEventVoiceStopped" = betterproto.message_field(
        25, group="event"
    )
    intent: "WyomingEventIntent" = betterproto.message_field(26, group="event")
    recognize: "WyomingEventRecognize" = betterproto.message_field(27, group="event")
    not_recognized: "WyomingEventNotRecognized" = betterproto.message_field(
        28, group="event"
    )
    handled: "WyomingEventHandled" = betterproto.message_field(29, group="event")
    not_handled: "WyomingEventNotHandled" = betterproto.message_field(30, group="event")
    timer_started: "WyomingEventTimerStarted" = betterproto.message_field(
        31, group="event"
    )
    timer_updated: "WyomingEventTimerUpdated" = betterproto.message_field(
        32, group="event"
    )
    timer_cancelled: "WyomingEventTimerCancelled" = betterproto.message_field(
        33, group="event"
    )
    timer_finished: "WyomingEventTimerFinished" = betterproto.message_field(
        34, group="event"
    )
    error: "WyomingEventError" = betterproto.message_field(35, group="event")
    other: "WyomingEventOther" = betterproto.message_field(36, group="event")


@dataclass(eq=False, repr=False)
class WyomingEventAttribution(betterproto.Message):
    name: str = betterproto.string_field(1)
    url: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WyomingEventAudioChunk(betterproto.Message):
    """generic model message, used in a few different contexts"""

    rate: int = betterproto.int64_field(1)
    width: int = betterproto.int64_field(2)
    channels: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class WyomingEventAudioStart(betterproto.Message):
    rate: int = betterproto.int64_field(1)
    width: int = betterproto.int64_field(2)
    channels: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class WyomingEventAudioStop(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventDescribe(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventDetect(betterproto.Message):
    names: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventDetection(betterproto.Message):
    name: str = betterproto.string_field(1)
    timestamp: int = betterproto.int64_field(2)
    speaker: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class WyomingEventNotDetected(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventInfo(betterproto.Message):
    asr: List["WyomingEventInfoAsrProgram"] = betterproto.message_field(1)
    tts: List["WyomingEventInfoTtsProgram"] = betterproto.message_field(2)
    handle: List["WyomingEventInfoHandleProgram"] = betterproto.message_field(3)
    intent: List["WyomingEventInfoIntentProgram"] = betterproto.message_field(4)
    wake: List["WyomingEventInfoWakeProgram"] = betterproto.message_field(5)
    mic: List["WyomingEventInfoMicProgram"] = betterproto.message_field(6)
    snd: List["WyomingEventInfoSndProgram"] = betterproto.message_field(7)
    satellite: "WyomingEventInfoSatellite" = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class WyomingEventInfoAsrProgram(betterproto.Message):
    models: List["WyomingEventInfoAsrProgramAsrModel"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventInfoAsrProgramAsrModel(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class WyomingEventInfoTtsProgram(betterproto.Message):
    voices: List["WyomingEventInfoTtsProgramTtsVoice"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventInfoTtsProgramTtsVoice(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)
    speakers: List["WyomingEventInfoTtsProgramTtsVoiceTtsVoiceSpeaker"] = (
        betterproto.message_field(7)
    )


@dataclass(eq=False, repr=False)
class WyomingEventInfoTtsProgramTtsVoiceTtsVoiceSpeaker(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventInfoHandleProgram(betterproto.Message):
    models: List["WyomingEventInfoHandleProgramHandleModel"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class WyomingEventInfoHandleProgramHandleModel(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class WyomingEventInfoIntentProgram(betterproto.Message):
    models: List["WyomingEventInfoIntentProgramIntentModel"] = (
        betterproto.message_field(1)
    )


@dataclass(eq=False, repr=False)
class WyomingEventInfoIntentProgramIntentModel(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class WyomingEventInfoWakeProgram(betterproto.Message):
    models: List["WyomingEventInfoWakeProgramWakeModel"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventInfoWakeProgramWakeModel(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)
    phrase: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class WyomingEventInfoAudioFormat(betterproto.Message):
    rate: int = betterproto.int64_field(1)
    width: int = betterproto.int64_field(2)
    channels: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class WyomingEventInfoMicProgram(betterproto.Message):
    models: List["WyomingEventInfoMicProgramMicModel"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventInfoMicProgramMicModel(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)
    mic_format: "WyomingEventInfoAudioFormat" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class WyomingEventInfoSndProgram(betterproto.Message):
    models: List["WyomingEventInfoSndProgramSndModel"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventInfoSndProgramSndModel(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)
    snd_format: "WyomingEventInfoAudioFormat" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class WyomingEventInfoSatellite(betterproto.Message):
    name: str = betterproto.string_field(1)
    languages: List[str] = betterproto.string_field(2)
    attribution: "WyomingEventAttribution" = betterproto.message_field(3)
    installed: bool = betterproto.bool_field(4)
    description: str = betterproto.string_field(5)
    version: str = betterproto.string_field(6)
    area: str = betterproto.string_field(7)
    has_vad: bool = betterproto.bool_field(8)
    active_wake_words: List[str] = betterproto.string_field(9)
    max_active_wake_words: int = betterproto.int64_field(10)
    supports_trigger: bool = betterproto.bool_field(11)


@dataclass(eq=False, repr=False)
class WyomingEventRunPipeline(betterproto.Message):
    start_stage: str = betterproto.string_field(1)
    end_stage: str = betterproto.string_field(2)
    wake_word_name: str = betterproto.string_field(3)
    wake_word_names: List[str] = betterproto.string_field(4)
    announce_text: str = betterproto.string_field(5)
    restart_on_end: bool = betterproto.bool_field(6)


@dataclass(eq=False, repr=False)
class WyomingEventRunSatellite(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventPauseSatellite(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventSatelliteConnected(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventSatelliteDisconnected(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventStreamingStarted(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventStreamingStopped(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventPlayed(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventPing(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventPong(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class WyomingEventTranscribe(betterproto.Message):
    name: str = betterproto.string_field(1)
    language: str = betterproto.string_field(2)
    context: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventTranscript(betterproto.Message):
    text: str = betterproto.string_field(1)
    context: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventSynthesize(betterproto.Message):
    text: str = betterproto.string_field(1)
    voice: "WyomingEventSynthesizeSynthesizeVoice" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class WyomingEventSynthesizeSynthesizeVoice(betterproto.Message):
    name: str = betterproto.string_field(1)
    language: str = betterproto.string_field(2)
    speaker: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class WyomingEventVoiceStarted(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventVoiceStopped(betterproto.Message):
    timestamp: int = betterproto.int64_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventIntent(betterproto.Message):
    name: str = betterproto.string_field(1)
    entities: List["WyomingEventIntentIntentEntity"] = betterproto.message_field(2)
    text: str = betterproto.string_field(3)
    context: Dict[str, str] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventIntentIntentEntity(betterproto.Message):
    name: str = betterproto.string_field(1)
    value: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WyomingEventRecognize(betterproto.Message):
    text: str = betterproto.string_field(1)
    context: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventNotRecognized(betterproto.Message):
    text: str = betterproto.string_field(1)
    context: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventHandled(betterproto.Message):
    text: str = betterproto.string_field(1)
    context: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventNotHandled(betterproto.Message):
    text: str = betterproto.string_field(1)
    context: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class WyomingEventTimerStarted(betterproto.Message):
    id: str = betterproto.string_field(1)
    total_seconds: int = betterproto.int64_field(2)
    name: str = betterproto.string_field(3)
    start_hours: int = betterproto.int64_field(4)
    start_minutes: int = betterproto.int64_field(5)
    start_seconds: int = betterproto.int64_field(6)
    command: "WyomingEventTimerStartedTimerCommand" = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class WyomingEventTimerStartedTimerCommand(betterproto.Message):
    text: str = betterproto.string_field(1)
    language: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WyomingEventTimerUpdated(betterproto.Message):
    id: str = betterproto.string_field(1)
    is_active: bool = betterproto.bool_field(2)
    total_seconds: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class WyomingEventTimerCancelled(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventTimerFinished(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class WyomingEventError(betterproto.Message):
    text: str = betterproto.string_field(1)
    code: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class WyomingEventOther(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ClientEvent(betterproto.Message):
    """Tell the server that a client event occurred"""

    media_player_state_change: "MediaPlayerStateChange" = betterproto.message_field(
        1, group="event"
    )
    media_player_volume_change: "MediaPlayerVolume" = betterproto.message_field(
        2, group="event"
    )
    device_volume_change: "DeviceVolume" = betterproto.message_field(3, group="event")
    log: "Log" = betterproto.message_field(4, group="event")
    wyoming_event: "WyomingEvent" = betterproto.message_field(5, group="event")


@dataclass(eq=False, repr=False)
class Log(betterproto.Message):
    """A log message passed from the client to the server"""

    log_text: str = betterproto.string_field(1)
    severity: "LogSeverity" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class ClientMessage(betterproto.Message):
    """The wrapper message that actually gets sent to the server"""

    ping: "Ping" = betterproto.message_field(1, group="msg")
    client_info: "ClientInfo" = betterproto.message_field(2, group="msg")
    audio_data: "AudioData" = betterproto.message_field(3, group="msg")
    client_event: "ClientEvent" = betterproto.message_field(4, group="msg")
    saved_settings: "SavedSettings" = betterproto.message_field(5, group="msg")


@dataclass(eq=False, repr=False)
class PlayAudio(betterproto.Message):
    """Play an audio file"""

    announce: bool = betterproto.bool_field(1)
    """Whether this should be an announcement or not"""

    url: str = betterproto.string_field(2)
    """The url to play"""


@dataclass(eq=False, repr=False)
class HassmicCommand(betterproto.Message):
    """
    The wrapper message that gets sent either from the server to the client or
     used internally between layers in the client
    """

    play_audio: "PlayAudio" = betterproto.message_field(1, group="msg")
    """A command to play audio"""

    set_mic_mute: bool = betterproto.bool_field(2, group="msg")
    """Set whether the mic should be muted"""

    set_device_volume: "DeviceVolume" = betterproto.message_field(3, group="msg")
    """Set the volume of the device"""

    set_player_volume: "MediaPlayerVolume" = betterproto.message_field(4, group="msg")
    """Set the volume of a player"""

    command: "MediaPlayerCommand" = betterproto.message_field(5, group="msg")
    """Play, pause, stop, etc"""

    set_wakeword_sound: str = betterproto.string_field(7, group="msg")
    """Wakeword"""

    internal: bool = betterproto.bool_field(6)
