syntax = "proto3";

package hassmic;

option java_package = "com.thejeffcooper.hassmic.proto";
option java_multiple_files = true;

// Information saved and loaded between runs of the hassmic app
message SavedSettings {
  // The last volume of the `announce` player
  optional float announce_volume = 1;

  // The last volume of the `playback` player
  optional float playback_volume = 2;

  // Hassmic UUID
  string hassmic_uuid = 3;

  // Device name
  string device_name = 4;

  // Wakeword Sound
  string wakeword_sound = 6;
}

// Information that the client sends about itself
message ClientInfo {
  // The version, for example "0.9.2"
  string version = 1;
  // The uuid of this client
  string uuid = 2;
}

// A ping message
message Ping {}

message AudioData { bytes data = 1; }

// https://developer.android.com/reference/androidx/media3/common/Player.State
enum MediaPlayerState {
  STATE_UNKNOWN = 0;
  STATE_IDLE = 1;
  STATE_BUFFERING = 2;
  STATE_PLAYING = 3;
  STATE_PAUSED = 4;
}

enum MediaPlayerCommandId {
  COMMAND_UNKNOWN = 0;
  COMMAND_PLAY = 1;
  COMMAND_PAUSE = 2;
  COMMAND_STOP = 3;
}

// A command paired with a player
message MediaPlayerCommand {
  MediaPlayerId id = 1;
  MediaPlayerCommandId command = 2;
}

// The different media players available
enum MediaPlayerId {
  ID_UNKNOWN = 0;

  // The normal music/audio playback player
  ID_PLAYBACK = 1;

  // The announce player
  ID_ANNOUNCE = 2;
}

// A media player has changed volume
message MediaPlayerVolume {
  MediaPlayerId player = 1;
  float volume = 2;
}

// The device volume has changed
message DeviceVolume { float volume = 1; }

// A media player has changed state
message MediaPlayerStateChange {
  MediaPlayerId player = 1;
  MediaPlayerState new_state = 2;
}

// An event from the wyoming server
// event definitions are captured from the wyoming project source
//
// up to date info messages are here, not the main page -
// https://github.com/rhasspy/wyoming/blob/master/wyoming/info.py
message WyomingEvent {
  // The raw json of the message
  string raw_json = 1;
  bytes payload = 2;

  message Attribution {
    string name = 1;
    string url = 2;
  }

  // generic model message, used in a few different contexts
  message AudioChunk {
    int64 rate = 1;
    int64 width = 2;
    int64 channels = 3;
  };

  message AudioStart {
    int64 rate = 1;
    int64 width = 2;
    int64 channels = 3;
  };

  message AudioStop {};

  message Describe {};

  message Detect { repeated string names = 1; };

  message Detection {
    string name = 1;
    int64 timestamp = 2;
    string speaker = 3;
  };

  message NotDetected {}

  message Info {
    message AsrProgram {
      message AsrModel {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
      }
      repeated AsrModel models = 1;
    }
    repeated AsrProgram asr = 1;

    message TtsProgram {
      message TtsVoice {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
        message TtsVoiceSpeaker { string name = 1; }
        repeated TtsVoiceSpeaker speakers = 7;
      }
      repeated TtsVoice voices = 1;
    }
    repeated TtsProgram tts = 2;

    message HandleProgram {
      message HandleModel {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
      }
      repeated HandleModel models = 1;
    }
    repeated HandleProgram handle = 3;

    message IntentProgram {
      message IntentModel {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
      }
      repeated IntentModel models = 1;
    }
    repeated IntentProgram intent = 4;

    message WakeProgram {
      message WakeModel {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
        string phrase = 7;
      }
      repeated WakeModel models = 1;
    }
    repeated WakeProgram wake = 5;

    message AudioFormat {
      int64 rate = 1;
      int64 width = 2;
      int64 channels = 3;
    }

    message MicProgram {
      message MicModel {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
        AudioFormat mic_format = 7;
      }
      repeated MicModel models = 1;
    }
    repeated MicProgram mic = 6;

    message SndProgram {
      message SndModel {
        string name = 1;
        repeated string languages = 2;
        Attribution attribution = 3;
        bool installed = 4;
        string description = 5;
        string version = 6;
        AudioFormat snd_format = 7;
      }
      repeated SndModel models = 1;
    }
    repeated SndProgram snd = 7;

    message Satellite {
      string name = 1;
      repeated string languages = 2;
      Attribution attribution = 3;
      bool installed = 4;
      string description = 5;
      string version = 6;
      string area = 7;
      bool has_vad = 8;
      repeated string active_wake_words = 9;
      int64 max_active_wake_words = 10;
      bool supports_trigger = 11;
    }
    Satellite satellite = 8;
  };

  message RunPipeline {
    string start_stage = 1;
    string end_stage = 2;
    string wake_word_name = 3;
    repeated string wake_word_names = 4;
    string announce_text = 5;
    bool restart_on_end = 6;
  }

  message RunSatellite {}
  message PauseSatellite {}
  message SatelliteConnected {}
  message SatelliteDisconnected {}
  message StreamingStarted {}
  message StreamingStopped {}
  message Played {}
  message Ping {}
  message Pong {}

  message Transcribe {
    string name = 1;
    string language = 2;
    map<string, string> context = 3;
  };

  message Transcript {
    string text = 1;
    map<string, string> context = 2;
  }

  message Synthesize {
    string text = 1;
    message SynthesizeVoice {
      string name = 1;
      string language = 2;
      string speaker = 3;
    }
    SynthesizeVoice voice = 2;
  }

  message VoiceStarted { int64 timestamp = 1; };
  message VoiceStopped { int64 timestamp = 1; };

  message Intent {
    string name = 1;
    message IntentEntity {
      string name = 1;
      string value = 2;
    }
    repeated IntentEntity entities = 2;
    string text = 3;
    map<string, string> context = 4;
  }

  message Recognize {
    string text = 1;
    map<string, string> context = 2;
  }

  message NotRecognized {
    string text = 1;
    map<string, string> context = 2;
  }

  message Handled {
    string text = 1;
    map<string, string> context = 2;
  }

  message NotHandled {
    string text = 1;
    map<string, string> context = 2;
  }

  message TimerStarted {
    string id = 1;
    int64 total_seconds = 2;
    string name = 3;
    int64 start_hours = 4;
    int64 start_minutes = 5;
    int64 start_seconds = 6;
    message TimerCommand {
      string text = 1;
      string language = 2;
    }
    TimerCommand command = 7;
  }

  message TimerUpdated {
    string id = 1;
    bool is_active = 2;
    int64 total_seconds = 3;
  }

  message TimerCancelled { string id = 1; }

  message TimerFinished { string id = 1; }

  message Error {
    string text = 1;
    string code = 2;
  }

  message Other {};

  oneof event {
    Describe describe = 3;
    Info info = 4;
    Ping ping = 5;
    Pong pong = 6;

    AudioChunk audio_chunk = 7;
    AudioStart audio_start = 8;
    AudioStop audio_stop = 9;
    Played played = 10;
    Detect detect = 11;
    Detection detection = 12;
    NotDetected not_detected = 13;

    RunPipeline run_pipeline = 14;
    RunSatellite run_satellite = 15;
    PauseSatellite pause_satellite = 16;
    SatelliteConnected satellite_connected = 17;
    SatelliteDisconnected satellite_disconnected = 18;
    StreamingStarted streaming_started = 19;
    StreamingStopped streaming_stopped = 20;

    Transcribe transcribe = 21;
    Transcript transcript = 22;
    Synthesize synthesize = 23;
    VoiceStarted voice_started = 24;
    VoiceStopped voice_stopped = 25;

    Intent intent = 26;
    Recognize recognize = 27;
    NotRecognized not_recognized = 28;

    Handled handled = 29;
    NotHandled not_handled = 30;

    TimerStarted timer_started = 31;
    TimerUpdated timer_updated = 32;
    TimerCancelled timer_cancelled = 33;
    TimerFinished timer_finished = 34;

    Error error = 35;
    Other other = 36;
  }
}

// Tell the server that a client event occurred
message ClientEvent {
  oneof event {
    MediaPlayerStateChange media_player_state_change = 1;
    MediaPlayerVolume media_player_volume_change = 2;
    DeviceVolume device_volume_change = 3;
    Log log = 4;
    WyomingEvent wyoming_event = 5;
  }
}

// A log message passed from the client to the server
message Log {
  enum Severity {
    SEVERITY_UNKNOWN = 0;
    SEVERITY_DEBUG = 1;
    SEVERITY_INFO = 2;
    SEVERITY_WARNING = 3;
    SEVERITY_ERROR = 4;
  }

  string log_text = 1;
  Severity severity = 2;
}

// The wrapper message that actually gets sent to the server
message ClientMessage {
  oneof msg {
    Ping ping = 1;
    ClientInfo client_info = 2;
    AudioData audio_data = 3; // deprecated!
    ClientEvent client_event = 4;
    SavedSettings saved_settings = 5;
  }
}

// Play an audio file
message PlayAudio {
  // Whether this should be an announcement or not
  bool announce = 1;

  // The url to play
  string url = 2;
}

// The wrapper message that gets sent either from the server to the client or
// used internally between layers in the client
message HassmicCommand {
  oneof msg {
    // A command to play audio
    PlayAudio play_audio = 1;

    // Set whether the mic should be muted
    bool set_mic_mute = 2;

    // Set the volume of the device
    DeviceVolume set_device_volume = 3;

    // Set the volume of a player
    MediaPlayerVolume set_player_volume = 4;

    // Play, pause, stop, etc
    MediaPlayerCommand command = 5;

    // Wakeword
    string set_wakeword_sound = 7;
  }
  bool internal = 6;
}
