// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 * <pre>
 * The wrapper message that gets sent either from the server to the client or
 * used internally between layers in the client
 * </pre>
 *
 * Protobuf type {@code hassmic.HassmicCommand}
 */
public  final class HassmicCommand extends
    com.google.protobuf.GeneratedMessageLite<
        HassmicCommand, HassmicCommand.Builder> implements
    // @@protoc_insertion_point(message_implements:hassmic.HassmicCommand)
    HassmicCommandOrBuilder {
  private HassmicCommand() {
  }
  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase {
    PLAY_AUDIO(1),
    SET_MIC_MUTE(2),
    SET_DEVICE_VOLUME(3),
    SET_PLAYER_VOLUME(4),
    COMMAND(5),
    SET_MIC_GAIN(6),
    SET_WAKEWORD_SOUND(7),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return PLAY_AUDIO;
        case 2: return SET_MIC_MUTE;
        case 3: return SET_DEVICE_VOLUME;
        case 4: return SET_PLAYER_VOLUME;
        case 5: return COMMAND;
        case 6: return SET_MIC_GAIN;
        case 7: return SET_WAKEWORD_SOUND;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  private void clearMsg() {
    msgCase_ = 0;
    msg_ = null;
  }

  public static final int PLAY_AUDIO_FIELD_NUMBER = 1;
  /**
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  @java.lang.Override
  public boolean hasPlayAudio() {
    return msgCase_ == 1;
  }
  /**
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.PlayAudio getPlayAudio() {
    if (msgCase_ == 1) {
       return (com.thejeffcooper.hassmic.proto.PlayAudio) msg_;
    }
    return com.thejeffcooper.hassmic.proto.PlayAudio.getDefaultInstance();
  }
  /**
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  private void setPlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
    value.getClass();
  msg_ = value;
    msgCase_ = 1;
  }
  /**
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  private void mergePlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
    value.getClass();
  if (msgCase_ == 1 &&
        msg_ != com.thejeffcooper.hassmic.proto.PlayAudio.getDefaultInstance()) {
      msg_ = com.thejeffcooper.hassmic.proto.PlayAudio.newBuilder((com.thejeffcooper.hassmic.proto.PlayAudio) msg_)
          .mergeFrom(value).buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 1;
  }
  /**
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  private void clearPlayAudio() {
    if (msgCase_ == 1) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_MIC_MUTE_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   * @return Whether the setMicMute field is set.
   */
  @java.lang.Override
  public boolean hasSetMicMute() {
    return msgCase_ == 2;
  }
  /**
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   * @return The setMicMute.
   */
  @java.lang.Override
  public boolean getSetMicMute() {
    if (msgCase_ == 2) {
      return (java.lang.Boolean) msg_;
    }
    return false;
  }
  /**
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   * @param value The setMicMute to set.
   */
  private void setSetMicMute(boolean value) {
    msgCase_ = 2;
    msg_ = value;
  }
  /**
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   */
  private void clearSetMicMute() {
    if (msgCase_ == 2) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_DEVICE_VOLUME_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
   */
  @java.lang.Override
  public boolean hasSetDeviceVolume() {
    return msgCase_ == 3;
  }
  /**
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.DeviceVolume getSetDeviceVolume() {
    if (msgCase_ == 3) {
       return (com.thejeffcooper.hassmic.proto.DeviceVolume) msg_;
    }
    return com.thejeffcooper.hassmic.proto.DeviceVolume.getDefaultInstance();
  }
  /**
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
   */
  private void setSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolume value) {
    value.getClass();
  msg_ = value;
    msgCase_ = 3;
  }
  /**
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
   */
  private void mergeSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolume value) {
    value.getClass();
  if (msgCase_ == 3 &&
        msg_ != com.thejeffcooper.hassmic.proto.DeviceVolume.getDefaultInstance()) {
      msg_ = com.thejeffcooper.hassmic.proto.DeviceVolume.newBuilder((com.thejeffcooper.hassmic.proto.DeviceVolume) msg_)
          .mergeFrom(value).buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 3;
  }
  /**
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
   */
  private void clearSetDeviceVolume() {
    if (msgCase_ == 3) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_PLAYER_VOLUME_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
   */
  @java.lang.Override
  public boolean hasSetPlayerVolume() {
    return msgCase_ == 4;
  }
  /**
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.MediaPlayerVolume getSetPlayerVolume() {
    if (msgCase_ == 4) {
       return (com.thejeffcooper.hassmic.proto.MediaPlayerVolume) msg_;
    }
    return com.thejeffcooper.hassmic.proto.MediaPlayerVolume.getDefaultInstance();
  }
  /**
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
   */
  private void setSetPlayerVolume(com.thejeffcooper.hassmic.proto.MediaPlayerVolume value) {
    value.getClass();
  msg_ = value;
    msgCase_ = 4;
  }
  /**
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
   */
  private void mergeSetPlayerVolume(com.thejeffcooper.hassmic.proto.MediaPlayerVolume value) {
    value.getClass();
  if (msgCase_ == 4 &&
        msg_ != com.thejeffcooper.hassmic.proto.MediaPlayerVolume.getDefaultInstance()) {
      msg_ = com.thejeffcooper.hassmic.proto.MediaPlayerVolume.newBuilder((com.thejeffcooper.hassmic.proto.MediaPlayerVolume) msg_)
          .mergeFrom(value).buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 4;
  }
  /**
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
   */
  private void clearSetPlayerVolume() {
    if (msgCase_ == 4) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Play, pause, stop, etc
   * </pre>
   *
   * <code>.hassmic.MediaPlayerCommand command = 5;</code>
   */
  @java.lang.Override
  public boolean hasCommand() {
    return msgCase_ == 5;
  }
  /**
   * <pre>
   * Play, pause, stop, etc
   * </pre>
   *
   * <code>.hassmic.MediaPlayerCommand command = 5;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.MediaPlayerCommand getCommand() {
    if (msgCase_ == 5) {
       return (com.thejeffcooper.hassmic.proto.MediaPlayerCommand) msg_;
    }
    return com.thejeffcooper.hassmic.proto.MediaPlayerCommand.getDefaultInstance();
  }
  /**
   * <pre>
   * Play, pause, stop, etc
   * </pre>
   *
   * <code>.hassmic.MediaPlayerCommand command = 5;</code>
   */
  private void setCommand(com.thejeffcooper.hassmic.proto.MediaPlayerCommand value) {
    value.getClass();
  msg_ = value;
    msgCase_ = 5;
  }
  /**
   * <pre>
   * Play, pause, stop, etc
   * </pre>
   *
   * <code>.hassmic.MediaPlayerCommand command = 5;</code>
   */
  private void mergeCommand(com.thejeffcooper.hassmic.proto.MediaPlayerCommand value) {
    value.getClass();
  if (msgCase_ == 5 &&
        msg_ != com.thejeffcooper.hassmic.proto.MediaPlayerCommand.getDefaultInstance()) {
      msg_ = com.thejeffcooper.hassmic.proto.MediaPlayerCommand.newBuilder((com.thejeffcooper.hassmic.proto.MediaPlayerCommand) msg_)
          .mergeFrom(value).buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 5;
  }
  /**
   * <pre>
   * Play, pause, stop, etc
   * </pre>
   *
   * <code>.hassmic.MediaPlayerCommand command = 5;</code>
   */
  private void clearCommand() {
    if (msgCase_ == 5) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_MIC_GAIN_FIELD_NUMBER = 6;
  /**
   * <pre>
   * Set the microphone gain
   * </pre>
   *
   * <code>float set_mic_gain = 6;</code>
   * @return Whether the setMicGain field is set.
   */
  @java.lang.Override
  public boolean hasSetMicGain() {
    return msgCase_ == 6;
  }
  /**
   * <pre>
   * Set the microphone gain
   * </pre>
   *
   * <code>float set_mic_gain = 6;</code>
   * @return The setMicGain.
   */
  @java.lang.Override
  public float getSetMicGain() {
    if (msgCase_ == 6) {
      return (java.lang.Float) msg_;
    }
    return 0F;
  }
  /**
   * <pre>
   * Set the microphone gain
   * </pre>
   *
   * <code>float set_mic_gain = 6;</code>
   * @param value The setMicGain to set.
   */
  private void setSetMicGain(float value) {
    msgCase_ = 6;
    msg_ = value;
  }
  /**
   * <pre>
   * Set the microphone gain
   * </pre>
   *
   * <code>float set_mic_gain = 6;</code>
   */
  private void clearSetMicGain() {
    if (msgCase_ == 6) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_WAKEWORD_SOUND_FIELD_NUMBER = 7;
  /**
   * <pre>
   * Wakeword
   * </pre>
   *
   * <code>string set_wakeword_sound = 7;</code>
   * @return Whether the setWakewordSound field is set.
   */
  @java.lang.Override
  public boolean hasSetWakewordSound() {
    return msgCase_ == 7;
  }
  /**
   * <pre>
   * Wakeword
   * </pre>
   *
   * <code>string set_wakeword_sound = 7;</code>
   * @return The setWakewordSound.
   */
  @java.lang.Override
  public java.lang.String getSetWakewordSound() {
    java.lang.String ref = "";
    if (msgCase_ == 7) {
      ref = (java.lang.String) msg_;
    }
    return ref;
  }
  /**
   * <pre>
   * Wakeword
   * </pre>
   *
   * <code>string set_wakeword_sound = 7;</code>
   * @return The bytes for setWakewordSound.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSetWakewordSoundBytes() {
    java.lang.String ref = "";
    if (msgCase_ == 7) {
      ref = (java.lang.String) msg_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <pre>
   * Wakeword
   * </pre>
   *
   * <code>string set_wakeword_sound = 7;</code>
   * @param value The setWakewordSound to set.
   */
  private void setSetWakewordSound(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  msgCase_ = 7;
    msg_ = value;
  }
  /**
   * <pre>
   * Wakeword
   * </pre>
   *
   * <code>string set_wakeword_sound = 7;</code>
   */
  private void clearSetWakewordSound() {
    if (msgCase_ == 7) {
      msgCase_ = 0;
      msg_ = null;
    }
  }
  /**
   * <pre>
   * Wakeword
   * </pre>
   *
   * <code>string set_wakeword_sound = 7;</code>
   * @param value The bytes for setWakewordSound to set.
   */
  private void setSetWakewordSoundBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    msg_ = value.toStringUtf8();
    msgCase_ = 7;
  }

  public static final int INTERNAL_FIELD_NUMBER = 8;
  private boolean internal_;
  /**
   * <code>bool internal = 8;</code>
   * @return The internal.
   */
  @java.lang.Override
  public boolean getInternal() {
    return internal_;
  }
  /**
   * <code>bool internal = 8;</code>
   * @param value The internal to set.
   */
  private void setInternal(boolean value) {
    
    internal_ = value;
  }
  /**
   * <code>bool internal = 8;</code>
   */
  private void clearInternal() {

    internal_ = false;
  }

  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.thejeffcooper.hassmic.proto.HassmicCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.thejeffcooper.hassmic.proto.HassmicCommand prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The wrapper message that gets sent either from the server to the client or
   * used internally between layers in the client
   * </pre>
   *
   * Protobuf type {@code hassmic.HassmicCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.thejeffcooper.hassmic.proto.HassmicCommand, Builder> implements
      // @@protoc_insertion_point(builder_implements:hassmic.HassmicCommand)
      com.thejeffcooper.hassmic.proto.HassmicCommandOrBuilder {
    // Construct using com.thejeffcooper.hassmic.proto.HassmicCommand.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MsgCase
        getMsgCase() {
      return instance.getMsgCase();
    }

    public Builder clearMsg() {
      copyOnWrite();
      instance.clearMsg();
      return this;
    }


    /**
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    @java.lang.Override
    public boolean hasPlayAudio() {
      return instance.hasPlayAudio();
    }
    /**
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.PlayAudio getPlayAudio() {
      return instance.getPlayAudio();
    }
    /**
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder setPlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
      copyOnWrite();
      instance.setPlayAudio(value);
      return this;
    }
    /**
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder setPlayAudio(
        com.thejeffcooper.hassmic.proto.PlayAudio.Builder builderForValue) {
      copyOnWrite();
      instance.setPlayAudio(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder mergePlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
      copyOnWrite();
      instance.mergePlayAudio(value);
      return this;
    }
    /**
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder clearPlayAudio() {
      copyOnWrite();
      instance.clearPlayAudio();
      return this;
    }

    /**
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     * @return Whether the setMicMute field is set.
     */
    @java.lang.Override
    public boolean hasSetMicMute() {
      return instance.hasSetMicMute();
    }
    /**
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     * @return The setMicMute.
     */
    @java.lang.Override
    public boolean getSetMicMute() {
      return instance.getSetMicMute();
    }
    /**
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     * @param value The setMicMute to set.
     * @return This builder for chaining.
     */
    public Builder setSetMicMute(boolean value) {
      copyOnWrite();
      instance.setSetMicMute(value);
      return this;
    }
    /**
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSetMicMute() {
      copyOnWrite();
      instance.clearSetMicMute();
      return this;
    }

    /**
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
     */
    @java.lang.Override
    public boolean hasSetDeviceVolume() {
      return instance.hasSetDeviceVolume();
    }
    /**
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.DeviceVolume getSetDeviceVolume() {
      return instance.getSetDeviceVolume();
    }
    /**
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
     */
    public Builder setSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolume value) {
      copyOnWrite();
      instance.setSetDeviceVolume(value);
      return this;
    }
    /**
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
     */
    public Builder setSetDeviceVolume(
        com.thejeffcooper.hassmic.proto.DeviceVolume.Builder builderForValue) {
      copyOnWrite();
      instance.setSetDeviceVolume(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
     */
    public Builder mergeSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolume value) {
      copyOnWrite();
      instance.mergeSetDeviceVolume(value);
      return this;
    }
    /**
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolume set_device_volume = 3;</code>
     */
    public Builder clearSetDeviceVolume() {
      copyOnWrite();
      instance.clearSetDeviceVolume();
      return this;
    }

    /**
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
     */
    @java.lang.Override
    public boolean hasSetPlayerVolume() {
      return instance.hasSetPlayerVolume();
    }
    /**
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.MediaPlayerVolume getSetPlayerVolume() {
      return instance.getSetPlayerVolume();
    }
    /**
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
     */
    public Builder setSetPlayerVolume(com.thejeffcooper.hassmic.proto.MediaPlayerVolume value) {
      copyOnWrite();
      instance.setSetPlayerVolume(value);
      return this;
    }
    /**
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
     */
    public Builder setSetPlayerVolume(
        com.thejeffcooper.hassmic.proto.MediaPlayerVolume.Builder builderForValue) {
      copyOnWrite();
      instance.setSetPlayerVolume(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
     */
    public Builder mergeSetPlayerVolume(com.thejeffcooper.hassmic.proto.MediaPlayerVolume value) {
      copyOnWrite();
      instance.mergeSetPlayerVolume(value);
      return this;
    }
    /**
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolume set_player_volume = 4;</code>
     */
    public Builder clearSetPlayerVolume() {
      copyOnWrite();
      instance.clearSetPlayerVolume();
      return this;
    }

    /**
     * <pre>
     * Play, pause, stop, etc
     * </pre>
     *
     * <code>.hassmic.MediaPlayerCommand command = 5;</code>
     */
    @java.lang.Override
    public boolean hasCommand() {
      return instance.hasCommand();
    }
    /**
     * <pre>
     * Play, pause, stop, etc
     * </pre>
     *
     * <code>.hassmic.MediaPlayerCommand command = 5;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.MediaPlayerCommand getCommand() {
      return instance.getCommand();
    }
    /**
     * <pre>
     * Play, pause, stop, etc
     * </pre>
     *
     * <code>.hassmic.MediaPlayerCommand command = 5;</code>
     */
    public Builder setCommand(com.thejeffcooper.hassmic.proto.MediaPlayerCommand value) {
      copyOnWrite();
      instance.setCommand(value);
      return this;
    }
    /**
     * <pre>
     * Play, pause, stop, etc
     * </pre>
     *
     * <code>.hassmic.MediaPlayerCommand command = 5;</code>
     */
    public Builder setCommand(
        com.thejeffcooper.hassmic.proto.MediaPlayerCommand.Builder builderForValue) {
      copyOnWrite();
      instance.setCommand(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Play, pause, stop, etc
     * </pre>
     *
     * <code>.hassmic.MediaPlayerCommand command = 5;</code>
     */
    public Builder mergeCommand(com.thejeffcooper.hassmic.proto.MediaPlayerCommand value) {
      copyOnWrite();
      instance.mergeCommand(value);
      return this;
    }
    /**
     * <pre>
     * Play, pause, stop, etc
     * </pre>
     *
     * <code>.hassmic.MediaPlayerCommand command = 5;</code>
     */
    public Builder clearCommand() {
      copyOnWrite();
      instance.clearCommand();
      return this;
    }

    /**
     * <pre>
     * Set the microphone gain
     * </pre>
     *
     * <code>float set_mic_gain = 6;</code>
     * @return Whether the setMicGain field is set.
     */
    @java.lang.Override
    public boolean hasSetMicGain() {
      return instance.hasSetMicGain();
    }
    /**
     * <pre>
     * Set the microphone gain
     * </pre>
     *
     * <code>float set_mic_gain = 6;</code>
     * @return The setMicGain.
     */
    @java.lang.Override
    public float getSetMicGain() {
      return instance.getSetMicGain();
    }
    /**
     * <pre>
     * Set the microphone gain
     * </pre>
     *
     * <code>float set_mic_gain = 6;</code>
     * @param value The setMicGain to set.
     * @return This builder for chaining.
     */
    public Builder setSetMicGain(float value) {
      copyOnWrite();
      instance.setSetMicGain(value);
      return this;
    }
    /**
     * <pre>
     * Set the microphone gain
     * </pre>
     *
     * <code>float set_mic_gain = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSetMicGain() {
      copyOnWrite();
      instance.clearSetMicGain();
      return this;
    }

    /**
     * <pre>
     * Wakeword
     * </pre>
     *
     * <code>string set_wakeword_sound = 7;</code>
     * @return Whether the setWakewordSound field is set.
     */
    @java.lang.Override
    public boolean hasSetWakewordSound() {
      return instance.hasSetWakewordSound();
    }
    /**
     * <pre>
     * Wakeword
     * </pre>
     *
     * <code>string set_wakeword_sound = 7;</code>
     * @return The setWakewordSound.
     */
    @java.lang.Override
    public java.lang.String getSetWakewordSound() {
      return instance.getSetWakewordSound();
    }
    /**
     * <pre>
     * Wakeword
     * </pre>
     *
     * <code>string set_wakeword_sound = 7;</code>
     * @return The bytes for setWakewordSound.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSetWakewordSoundBytes() {
      return instance.getSetWakewordSoundBytes();
    }
    /**
     * <pre>
     * Wakeword
     * </pre>
     *
     * <code>string set_wakeword_sound = 7;</code>
     * @param value The setWakewordSound to set.
     * @return This builder for chaining.
     */
    public Builder setSetWakewordSound(
        java.lang.String value) {
      copyOnWrite();
      instance.setSetWakewordSound(value);
      return this;
    }
    /**
     * <pre>
     * Wakeword
     * </pre>
     *
     * <code>string set_wakeword_sound = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSetWakewordSound() {
      copyOnWrite();
      instance.clearSetWakewordSound();
      return this;
    }
    /**
     * <pre>
     * Wakeword
     * </pre>
     *
     * <code>string set_wakeword_sound = 7;</code>
     * @param value The bytes for setWakewordSound to set.
     * @return This builder for chaining.
     */
    public Builder setSetWakewordSoundBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSetWakewordSoundBytes(value);
      return this;
    }

    /**
     * <code>bool internal = 8;</code>
     * @return The internal.
     */
    @java.lang.Override
    public boolean getInternal() {
      return instance.getInternal();
    }
    /**
     * <code>bool internal = 8;</code>
     * @param value The internal to set.
     * @return This builder for chaining.
     */
    public Builder setInternal(boolean value) {
      copyOnWrite();
      instance.setInternal(value);
      return this;
    }
    /**
     * <code>bool internal = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearInternal() {
      copyOnWrite();
      instance.clearInternal();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:hassmic.HassmicCommand)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.thejeffcooper.hassmic.proto.HassmicCommand();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "msg_",
            "msgCase_",
            com.thejeffcooper.hassmic.proto.PlayAudio.class,
            com.thejeffcooper.hassmic.proto.DeviceVolume.class,
            com.thejeffcooper.hassmic.proto.MediaPlayerVolume.class,
            com.thejeffcooper.hassmic.proto.MediaPlayerCommand.class,
            "internal_",
          };
          java.lang.String info =
              "\u0000\b\u0001\u0000\u0001\b\b\u0000\u0000\u0000\u0001<\u0000\u0002:\u0000\u0003" +
              "<\u0000\u0004<\u0000\u0005<\u0000\u00064\u0000\u0007\u023b\u0000\b\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.thejeffcooper.hassmic.proto.HassmicCommand> parser = PARSER;
        if (parser == null) {
          synchronized (com.thejeffcooper.hassmic.proto.HassmicCommand.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.thejeffcooper.hassmic.proto.HassmicCommand>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:hassmic.HassmicCommand)
  private static final com.thejeffcooper.hassmic.proto.HassmicCommand DEFAULT_INSTANCE;
  static {
    HassmicCommand defaultInstance = new HassmicCommand();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HassmicCommand.class, defaultInstance);
  }

  public static com.thejeffcooper.hassmic.proto.HassmicCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HassmicCommand> PARSER;

  public static com.google.protobuf.Parser<HassmicCommand> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

